LineLength:
  Enabled: false
Encoding:
  Enabled: false
Documentation:
  Enabled: false
NumericLiterals:
  Enabled: false
NumericLiterals:
  Enabled: false  

AllCops:
  Excludes:
    - db/**
    - config/**
